<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Quiz extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'study_card_id',
        'title',
        'description',
        'total_questions',
        'duration_minutes',
        'generated_by_ai',
        'ai_model',
        'shuffle_questions',
        'shuffle_answers',
        'show_correct_answers',
    ];

    protected $casts = [
        'total_questions' => 'integer',
        'duration_minutes' => 'integer',
        'generated_by_ai' => 'boolean',
        'shuffle_questions' => 'boolean',
        'shuffle_answers' => 'boolean',
        'show_correct_answers' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    // Relationships
    public function studyCard()
    {
        return $this->belongsTo(StudyCard::class);
    }

    public function questions()
    {
        return $this->hasMany(QuizQuestion::class)->orderBy('order_number');
    }

    public function attempts()
    {
        return $this->hasMany(UserQuizAttempt::class);
    }

    // Get quiz owner through study card
    public function owner()
    {
        return $this->hasOneThrough(User::class, StudyCard::class, 'id', 'id', 'study_card_id', 'user_id');
    }

    // Check if quiz was generated by AI
    public function isAiGenerated()
    {
        return $this->generated_by_ai === true;
    }

    // Get quiz duration in human readable format
    public function getDurationFormattedAttribute()
    {
        if (!$this->duration_minutes) return 'No time limit';
        
        if ($this->duration_minutes < 60) {
            return $this->duration_minutes . ' minutes';
        }
        
        $hours = floor($this->duration_minutes / 60);
        $minutes = $this->duration_minutes % 60;
        
        return $hours . 'h ' . $minutes . 'm';
    }
}